-- ============================================================================
--  Madama Group - System 2 seed data, migrated from the Google Sheets workbook.
--  Idempotent: re-running updates the existing rows instead of duplicating them.
--  default_cta line breaks are restored from the flat export using the fixed
--  label list (Phone:/Email:/Website:/...), verified against the raw CSV export.
-- ============================================================================


-- ---------- brands: 4 rows ----------
insert into public.brands (brand_id, company_name, brand_context, target_audience, tone_of_voice, default_cta, timezone, active, publish_facebook, publish_instagram, publish_linkedin, facebook_page_id, instagram_user_id, linkedin_organization_id, website_url, contact_email, contact_phone, connection_status, created_at, updated_at, facebook_url, instagram_url, linkedin_url, messenger_url, whatsapp_url, yelp_url, logo_url, brand_primary_color, brand_secondary_color, image_branding_instructions) values
  ($q$jayco$q$, $q$Jayco Maintenance$q$, $q$Jayco Maintenance Group provides professional residential and commercial services across the United States. Approved service categories for marketing are Plumber, Electrical, HVAC, Handyman, Appliance Repair, Locksmith, Glass Repair, Power Washing, Landscaping, Snow Removal, and Junk Removal. Create commercially focused service content using only the selected category and supplied company facts. Emphasize responsive coordination, clear communication, and customer-focused support. Do not claim 24/7 availability, prices, guarantees, certifications, or unsupported results.$q$, $q$Homeowners, tenants, landlords, residential communities, property managers, facility managers, retail chains, store managers, operations teams, organizations, and residential or commercial property owners across the United States.$q$, $q$Professional, dependable, helpful, clear, responsive, customer-focused, and solution-oriented.$q$, $q$REQUEST SERVICE
Phone: +1 830-400-0200
Email: dispatch@jaycomaintenancegroup.com
Website: https://jaycomaintenancegroup.com
Facebook: https://www.facebook.com/jaycomaintenancegroup
Messenger: https://www.facebook.com/messages/t/jaycomaintenancegroup/
LinkedIn: https://www.linkedin.com/company/jayco-maintenance-group
Yelp: https://www.yelp.com/biz/jayco-maintenance-group-houston$q$, $q$America/New_York$q$, true, false, false, false, $q$$q$, $q$$q$, $q$$q$, $q$https://jaycomaintenancegroup.com$q$, $q$dispatch@jaycomaintenancegroup.com$q$, $q$\+1 830-400-0200$q$, $q$$q$, $q$$q$, $q$$q$, $q$https://www.facebook.com/jaycomaintenancegroup$q$, $q$$q$, $q$https://www.linkedin.com/company/jayco-maintenance-group$q$, $q$https://www.facebook.com/messages/t/jaycomaintenancegroup/$q$, $q$$q$, $q$https://www.yelp.com/biz/jayco-maintenance-group-houston$q$, $q$$q$, $q$$q$, $q$$q$, $q$$q$),
  ($q$smply$q$, $q$Simply Facility Solutions$q$, $q$Simply Facility Solutions provides facility construction and maintenance services in Chicago. Website-verified services are Handyman, Electrical, HVAC, and Locksmith for residential and commercial properties; the Electrical page also references industrial work. Create content only from these verified services and website facts. Do not claim 24/7 or emergency availability, nationwide coverage, prices, guarantees, certifications, or unsupported results.$q$, $q$Chicago-area property owners, homeowners, landlords, property managers, facility managers, commercial operators, and organizations seeking construction, maintenance, electrical, HVAC, handyman, or locksmith support.$q$, $q$Professional, approachable, practical, clear, polished, and service-focused.$q$, $q$REQUEST SERVICE
Phone: (440) 737-2732
Email: service@simply-fs.com
Website: https://www.simply-fs.com/$q$, $q$America/Chicago$q$, true, false, false, false, $q$$q$, $q$$q$, $q$$q$, $q$https://www.simply-fs.com/$q$, $q$service@simply-fs.com$q$, $q$(440) 737-2732$q$, $q$Connection Pending$q$, $q$2026-08-29T00:00:00.000Z$q$, $q$2026-08-29T00:00:00.000Z$q$, $q$$q$, $q$$q$, $q$$q$, $q$$q$, $q$$q$, $q$$q$, $q$$q$, $q$\#146FAF$q$, $q$\#8EB6DC$q$, $q$Use a clean contemporary Simply identity: light blue (\#8EB6DC), deeper blue (\#146FAF), black, white, and pale gray; uncluttered compositions, bright natural light, modern Chicago residential or commercial settings, and technicians presented neatly and professionally. Do not invent a logo or fake wordmark. Leave clear negative space in a corner for the official Simply Facility Solutions wordmark overlay.$q$),
  ($q$huax$q$, $q$Hawks Facility Solutions$q$, $q$Hawks Facility Solutions is a New York City-based nationwide commercial facility services provider supporting multi-site operations 24/7/365. Website-verified services include preventive maintenance, emergency repairs, building maintenance, HVAC, electrical, plumbing, appliances, construction, doors and locksmith, general contracting, glass, and vendor/facility support. Specialized website-listed work includes pressure testing, hydro jetting, drain snaking, camera inspections, septic work, rekeying, lock replacement, door hardware and replacement, flooring, board-up, tiling, and carpentry. Use only verified website facts; do not invent prices, certifications, guarantees, or performance results.$q$, $q$Facility managers, property managers, operations leaders, procurement teams, retail and multi-site operators, corporate offices, commercial buildings, residential communities, industrial facilities, healthcare properties, and education facilities across the United States.$q$, $q$Professional, responsive, accountable, operational, confident, clear, and solution-oriented.$q$, $q$REQUEST SERVICE
Phone: (888) 818-8110
Email: dispatch@hawksfs.com
Website: https://hawksfs.com/$q$, $q$America/New_York$q$, true, false, false, false, $q$$q$, $q$$q$, $q$$q$, $q$https://hawksfs.com/$q$, $q$dispatch@hawksfs.com$q$, $q$(888) 818-8110$q$, $q$Connection Pending$q$, $q$2026-08-29T00:00:00.000Z$q$, $q$2026-08-29T00:00:00.000Z$q$, $q$$q$, $q$$q$, $q$$q$, $q$$q$, $q$$q$, $q$$q$, $q$https://hawksfs.com/wp-content/themes/hawks-theme/content/hawkslogo.png$q$, $q$\#0F4C81$q$, $q$\#001F3F$q$, $q$Use Hawks' official visual system: primary blue \#0F4C81, deep navy \#001F3F, white, and light slate. Show realistic commercial facilities and skilled technicians in clean navy/blue workwear, with confident operational compositions and crisp natural lighting. Do not invent or redraw the logo. Leave clean negative space for deterministic placement of the official Hawks logo.$q$),
  ($q$paip$q$, $q$Pipes & Wires$q$, $q$Pipes & Wires is a Dallas-based commercial facility maintenance company serving Texas, Louisiana, Oklahoma, and Arizona 24/7/365. Website-verified services are HVAC installation, repair, diagnostics, and preventive maintenance; Electrical; Plumbing; General Maintenance; Metal Studs & Framing; and Cameras & Speed Radar, including security/CCTV and road camera applications. Create content only from these verified services and the four-state coverage. Do not claim nationwide coverage, prices, guarantees, certifications, or unsupported results.$q$, $q$Facility managers, property managers, operations teams, retail and multi-site operators, commercial buildings, offices, residential communities, warehouses and industrial facilities, healthcare properties, and education facilities in Texas, Louisiana, Oklahoma, and Arizona.$q$, $q$Professional, direct, dependable, technical, responsive, clear, and operations-focused.$q$, $q$REQUEST SERVICE
Phone: +1 (469) 949-5081
Email: service@pipeswires.com
Website: https://pipeswires.com/$q$, $q$America/Chicago$q$, true, false, false, false, $q$$q$, $q$$q$, $q$$q$, $q$https://pipeswires.com/$q$, $q$service@pipeswires.com$q$, $q$\+1 (469) 949-5081$q$, $q$Connection Pending$q$, $q$2026-08-29T00:00:00.000Z$q$, $q$2026-08-29T00:00:00.000Z$q$, $q$$q$, $q$$q$, $q$$q$, $q$$q$, $q$$q$, $q$$q$, $q$https://pipeswires.com/wp-content/themes/hawks-theme/content/hawkslogo.png$q$, $q$\#0B2545$q$, $q$\#F4BC1C$q$, $q$Use Pipes & Wires' visual identity: deep navy \#0B2545, safety yellow \#F4BC1C, white, and warm off-white. Feature realistic commercial trades, systems, tools, and technicians with navy uniforms and restrained yellow accents; use strong clean geometry and practical worksite lighting. Do not invent or redraw the logo. Leave clean negative space for deterministic placement of the official Pipes & Wires logo.$q$)
on conflict (brand_id) do update set company_name = excluded.company_name, brand_context = excluded.brand_context, target_audience = excluded.target_audience, tone_of_voice = excluded.tone_of_voice, default_cta = excluded.default_cta, timezone = excluded.timezone, active = excluded.active, publish_facebook = excluded.publish_facebook, publish_instagram = excluded.publish_instagram, publish_linkedin = excluded.publish_linkedin, facebook_page_id = excluded.facebook_page_id, instagram_user_id = excluded.instagram_user_id, linkedin_organization_id = excluded.linkedin_organization_id, website_url = excluded.website_url, contact_email = excluded.contact_email, contact_phone = excluded.contact_phone, connection_status = excluded.connection_status, created_at = excluded.created_at, updated_at = excluded.updated_at, facebook_url = excluded.facebook_url, instagram_url = excluded.instagram_url, linkedin_url = excluded.linkedin_url, messenger_url = excluded.messenger_url, whatsapp_url = excluded.whatsapp_url, yelp_url = excluded.yelp_url, logo_url = excluded.logo_url, brand_primary_color = excluded.brand_primary_color, brand_secondary_color = excluded.brand_secondary_color, image_branding_instructions = excluded.image_branding_instructions;

-- ---------- brand_content_options: 47 rows ----------
insert into public.brand_content_options (option_id, brand_id, content_type, category, option_label, option_value, active, sort_order, notes) values
  ($q$occasion-new-year$q$, $q$all$q$, $q$occasion$q$, $q$general$q$, $q$New Year$q$, $q$New Year$q$, true, 1, $q$General occasion$q$),
  ($q$occasion-labor-day$q$, $q$all$q$, $q$occasion$q$, $q$general$q$, $q$Labor Day$q$, $q$Labor Day$q$, true, 2, $q$General U.S. occasion$q$),
  ($q$occasion-thanksgiving$q$, $q$all$q$, $q$occasion$q$, $q$general$q$, $q$Thanksgiving$q$, $q$Thanksgiving$q$, true, 3, $q$General U.S. occasion$q$),
  ($q$occasion-independence-day$q$, $q$all$q$, $q$occasion$q$, $q$general$q$, $q$U.S. Independence Day$q$, $q$U.S. Independence Day$q$, true, 4, $q$General U.S. occasion$q$),
  ($q$occasion-womens-day$q$, $q$all$q$, $q$occasion$q$, $q$general$q$, $q$International Women's Day$q$, $q$International Women's Day$q$, true, 5, $q$General occasion$q$),
  ($q$occasion-ramadan$q$, $q$all$q$, $q$occasion$q$, $q$islamic$q$, $q$Ramadan$q$, $q$Ramadan$q$, true, 1, $q$Islamic occasion$q$),
  ($q$occasion-eid-fitr$q$, $q$all$q$, $q$occasion$q$, $q$islamic$q$, $q$Eid al-Fitr$q$, $q$Eid al-Fitr$q$, true, 2, $q$Islamic occasion$q$),
  ($q$occasion-eid-adha$q$, $q$all$q$, $q$occasion$q$, $q$islamic$q$, $q$Eid al-Adha$q$, $q$Eid al-Adha$q$, true, 3, $q$Islamic occasion$q$),
  ($q$occasion-islamic-new-year$q$, $q$all$q$, $q$occasion$q$, $q$islamic$q$, $q$Islamic New Year$q$, $q$Islamic New Year$q$, true, 4, $q$Islamic occasion$q$),
  ($q$occasion-mawlid$q$, $q$all$q$, $q$occasion$q$, $q$islamic$q$, $q$Mawlid al-Nabi$q$, $q$Mawlid al-Nabi$q$, true, 5, $q$Islamic occasion$q$),
  ($q$occasion-christmas$q$, $q$all$q$, $q$occasion$q$, $q$christian$q$, $q$Christmas$q$, $q$Christmas$q$, true, 1, $q$Christian occasion$q$),
  ($q$occasion-easter$q$, $q$all$q$, $q$occasion$q$, $q$christian$q$, $q$Easter$q$, $q$Easter$q$, true, 2, $q$Christian occasion$q$),
  ($q$occasion-good-friday$q$, $q$all$q$, $q$occasion$q$, $q$christian$q$, $q$Good Friday$q$, $q$Good Friday$q$, true, 3, $q$Christian occasion$q$),
  ($q$occasion-palm-sunday$q$, $q$all$q$, $q$occasion$q$, $q$christian$q$, $q$Palm Sunday$q$, $q$Palm Sunday$q$, true, 4, $q$Christian occasion$q$),
  ($q$jayco-plumber$q$, $q$jayco$q$, $q$service$q$, $q$technical$q$, $q$Plumber$q$, $q$Plumber$q$, true, 1, $q$Residential and commercial plumbing service$q$),
  ($q$jayco-electrical$q$, $q$jayco$q$, $q$service$q$, $q$technical$q$, $q$Electrical$q$, $q$Electrical$q$, true, 2, $q$Residential and commercial electrical service$q$),
  ($q$jayco-hvac$q$, $q$jayco$q$, $q$service$q$, $q$technical$q$, $q$HVAC$q$, $q$HVAC$q$, true, 3, $q$Heating, ventilation, and air-conditioning service$q$),
  ($q$jayco-handyman$q$, $q$jayco$q$, $q$service$q$, $q$technical$q$, $q$Handyman$q$, $q$Handyman$q$, true, 4, $q$General handyman service$q$),
  ($q$jayco-appliance-repair$q$, $q$jayco$q$, $q$service$q$, $q$technical$q$, $q$Appliance Repair$q$, $q$Appliance Repair$q$, true, 5, $q$Appliance repair service$q$),
  ($q$jayco-locksmith$q$, $q$jayco$q$, $q$service$q$, $q$technical$q$, $q$Locksmith$q$, $q$Locksmith$q$, true, 6, $q$Residential and commercial locksmith service$q$),
  ($q$jayco-glass-repair$q$, $q$jayco$q$, $q$service$q$, $q$technical$q$, $q$Glass Repair$q$, $q$Glass Repair$q$, true, 7, $q$Glass repair service$q$),
  ($q$jayco-power-washing$q$, $q$jayco$q$, $q$service$q$, $q$technical$q$, $q$Power Washing$q$, $q$Power Washing$q$, true, 8, $q$Exterior power-washing service$q$),
  ($q$jayco-landscaping$q$, $q$jayco$q$, $q$service$q$, $q$technical$q$, $q$Landscaping$q$, $q$Landscaping$q$, true, 9, $q$Landscaping service$q$),
  ($q$jayco-snow-removal$q$, $q$jayco$q$, $q$service$q$, $q$technical$q$, $q$Snow Removal$q$, $q$Snow Removal$q$, true, 10, $q$Snow-removal service$q$),
  ($q$jayco-junk-removal$q$, $q$jayco$q$, $q$service$q$, $q$technical$q$, $q$Junk Removal$q$, $q$Junk Removal$q$, true, 11, $q$Junk-removal service$q$),
  ($q$huax-preventive-maintenance$q$, $q$huax$q$, $q$service$q$, $q$technical$q$, $q$Preventive Maintenance$q$, $q$Preventive Maintenance$q$, true, 1, $q$Planned facility inspections and recurring upkeep$q$),
  ($q$huax-emergency-repairs$q$, $q$huax$q$, $q$service$q$, $q$technical$q$, $q$Emergency Repairs$q$, $q$Emergency Repairs$q$, true, 2, $q$24/7/365 commercial emergency repair response$q$),
  ($q$huax-building-maintenance$q$, $q$huax$q$, $q$service$q$, $q$technical$q$, $q$Building Maintenance$q$, $q$Building Maintenance$q$, true, 3, $q$Ongoing commercial building maintenance$q$),
  ($q$huax-hvac$q$, $q$huax$q$, $q$service$q$, $q$technical$q$, $q$HVAC$q$, $q$HVAC$q$, true, 4, $q$Commercial heating, ventilation, and air-conditioning service$q$),
  ($q$huax-electrical$q$, $q$huax$q$, $q$service$q$, $q$technical$q$, $q$Electrical$q$, $q$Electrical$q$, true, 5, $q$Commercial electrical service$q$),
  ($q$huax-plumbing$q$, $q$huax$q$, $q$service$q$, $q$technical$q$, $q$Plumbing$q$, $q$Plumbing$q$, true, 6, $q$Commercial plumbing and specialized drain/septic work$q$),
  ($q$huax-appliances$q$, $q$huax$q$, $q$service$q$, $q$technical$q$, $q$Appliances$q$, $q$Appliances$q$, true, 7, $q$Commercial appliance service$q$),
  ($q$huax-construction$q$, $q$huax$q$, $q$service$q$, $q$technical$q$, $q$Construction$q$, $q$Construction$q$, true, 8, $q$Commercial construction support$q$),
  ($q$huax-doors-locksmith$q$, $q$huax$q$, $q$service$q$, $q$technical$q$, $q$Doors & Locksmith$q$, $q$Doors & Locksmith$q$, true, 9, $q$Commercial doors, locks, rekeying, and hardware$q$),
  ($q$huax-general-contracting$q$, $q$huax$q$, $q$service$q$, $q$technical$q$, $q$General Contracting$q$, $q$General Contracting$q$, true, 10, $q$General contracting and finish work$q$),
  ($q$huax-glass$q$, $q$huax$q$, $q$service$q$, $q$technical$q$, $q$Glass$q$, $q$Glass$q$, true, 11, $q$Commercial glass service$q$),
  ($q$huax-vendor-facility-support$q$, $q$huax$q$, $q$service$q$, $q$technical$q$, $q$Vendor & Facility Support$q$, $q$Vendor & Facility Support$q$, true, 12, $q$Nationwide vendor coordination and facility support$q$),
  ($q$paip-hvac$q$, $q$paip$q$, $q$service$q$, $q$technical$q$, $q$HVAC$q$, $q$HVAC$q$, true, 1, $q$Installation, repair, diagnostics, and preventive maintenance$q$),
  ($q$paip-electrical$q$, $q$paip$q$, $q$service$q$, $q$technical$q$, $q$Electrical$q$, $q$Electrical$q$, true, 2, $q$Commercial electrical service$q$),
  ($q$paip-plumbing$q$, $q$paip$q$, $q$service$q$, $q$technical$q$, $q$Plumbing$q$, $q$Plumbing$q$, true, 3, $q$Commercial plumbing service$q$),
  ($q$paip-general-maintenance$q$, $q$paip$q$, $q$service$q$, $q$technical$q$, $q$General Maintenance$q$, $q$General Maintenance$q$, true, 4, $q$Day-to-day commercial facility maintenance$q$),
  ($q$paip-metal-studs-framing$q$, $q$paip$q$, $q$service$q$, $q$technical$q$, $q$Metal Studs & Framing$q$, $q$Metal Studs & Framing$q$, true, 5, $q$Commercial metal stud and framing work$q$),
  ($q$paip-cameras-speed-radar$q$, $q$paip$q$, $q$service$q$, $q$technical$q$, $q$Cameras & Speed Radar$q$, $q$Cameras & Speed Radar$q$, true, 6, $q$Security/CCTV, road cameras, and speed radar systems$q$),
  ($q$smply-handyman$q$, $q$smply$q$, $q$service$q$, $q$technical$q$, $q$Handyman$q$, $q$Handyman$q$, true, 1, $q$Residential and commercial handyman service$q$),
  ($q$smply-electrical$q$, $q$smply$q$, $q$service$q$, $q$technical$q$, $q$Electrical$q$, $q$Electrical$q$, true, 2, $q$Residential, commercial, and industrial electrical work$q$),
  ($q$smply-hvac$q$, $q$smply$q$, $q$service$q$, $q$technical$q$, $q$HVAC$q$, $q$HVAC$q$, true, 3, $q$Residential and commercial HVAC service$q$),
  ($q$smply-locksmith$q$, $q$smply$q$, $q$service$q$, $q$technical$q$, $q$Locksmith$q$, $q$Locksmith$q$, true, 4, $q$Residential and commercial locksmith service$q$)
on conflict (option_id) do update set brand_id = excluded.brand_id, content_type = excluded.content_type, category = excluded.category, option_label = excluded.option_label, option_value = excluded.option_value, active = excluded.active, sort_order = excluded.sort_order, notes = excluded.notes;

-- ---------- service_details: 33 rows ----------
insert into public.service_details (brand_id, service_value, summary, scenarios, differentiators, keywords, avoid) values
  ($q$jayco$q$, $q$Plumber$q$, $q$Commercial plumbing: installation, maintenance, and repair of pipes, fixtures, and fittings for water supply and wastewater removal (copper, PVC, galvanized steel).$q$, $q$Faucets, toilets, sinks, showers, water heaters, drain clogs, leaks, and drainage/sewage systems for offices, restaurants, industrial, and public facilities.$q$, $q$Fast resolution to keep facilities open; protects staff and customers; conserves water; nationwide coverage across all 50 states.$q$, $q$commercial plumbing, leaks, drains, water heaters, fixtures, wastewater$q$, $q$24/7 claims; prices; guarantees; certifications; residential/home framing; DIY how-to$q$),
  ($q$jayco$q$, $q$Electrical$q$, $q$Commercial electrical service keeping business systems powered and reliable: troubleshooting, repairs, lighting, and panel/fixture upgrades, performed safely and up to code.$q$, $q$Restoring power to essential equipment, lighting, panel and fixture upgrades, and communication systems in commercial spaces.$q$, $q$Safe, code-compliant work; nationwide dispatch; minimizes operational disruption.$q$, $q$commercial electrical, lighting, panel upgrade, troubleshooting, up to code$q$, $q$24/7 claims; prices; guarantees; certifications; residential/home framing; DIY how-to$q$),
  ($q$jayco$q$, $q$HVAC$q$, $q$Commercial HVAC (heating, ventilation, air conditioning) controlling the indoor environment of commercial buildings: maintenance, repairs, and replacements.$q$, $q$Climate control and indoor air quality for offices, retail spaces, restaurants, and industrial facilities.$q$, $q$Year-round comfort; nationwide dispatch; suited to multi-industry facilities.$q$, $q$commercial HVAC, heating, cooling, ventilation, indoor air quality$q$, $q$24/7 claims; prices; guarantees; certifications; residential/home framing; DIY how-to$q$),
  ($q$jayco$q$, $q$Appliance Repair$q$, $q$Commercial appliance repair focused on commercial refrigeration (reach-in coolers, glass-door merchandisers, display cases, walk-in freezers, ice machines) plus the full range of business appliances.$q$, $q$Diagnosis, repair, and preventive maintenance for kitchens, break rooms, and facilities; preventing lost inventory and downtime.$q$, $q$One call covers diagnosis, repair, and preventive maintenance; minimizes downtime; nationwide.$q$, $q$commercial refrigeration, coolers, freezers, ice machines, appliance repair$q$, $q$24/7 claims; prices; guarantees; certifications; residential/home framing; DIY how-to$q$),
  ($q$jayco$q$, $q$Handyman$q$, $q$Commercial general handyman handling a wide range of repairs and everyday fixes: punch lists, fixture swaps, drywall, and doors for commercial properties.$q$, $q$Punch lists, fixture swaps, drywall, doors, and everyday commercial property fixes; coordinates with plumbing, electrical, HVAC, appliance, and locksmith trades.$q$, $q$One call covers many tasks; reliable for busy commercial operations; nationwide.$q$, $q$commercial handyman, punch list, drywall, doors, fixture repair$q$, $q$24/7 claims; prices; guarantees; certifications; residential/home framing; DIY how-to$q$),
  ($q$jayco$q$, $q$Locksmith$q$, $q$Commercial locksmith: installation, repair, and maintenance of commercial doors, locks, and security hardware, including mechanical, electronic, and smart locks and master-key systems.$q$, $q$Rekeying, master-key systems, access hardware, and door/lock repair for offices, commercial properties, and business fleets.$q$, $q$Keeps facilities and people secure; rapid technician dispatch; nationwide.$q$, $q$commercial locksmith, rekey, master key, access control, door hardware$q$, $q$24/7 claims; prices; guarantees; certifications; residential/home framing; DIY how-to$q$),
  ($q$jayco$q$, $q$Glass Repair$q$, $q$Commercial glass repair and replacement for storefronts, entry doors, partitions, and windows across commercial properties.$q$, $q$Cracked or broken storefront glass, damaged glass doors, office partition glass, and window pane replacement for offices, retail, and facilities.$q$, $q$Restores security and appearance quickly to keep businesses operating; nationwide coverage across all 50 states.$q$, $q$commercial glass repair, storefront glass, window replacement, glass door, partitions$q$, $q$24/7 claims; prices; guarantees; certifications; residential/home framing; DIY how-to$q$),
  ($q$jayco$q$, $q$Power Washing$q$, $q$Commercial power washing and exterior cleaning for building facades, walkways, parking areas, and entrances.$q$, $q$Removing dirt, grime, gum, and stains from storefronts, sidewalks, loading docks, and parking lots for retail, offices, and facilities.$q$, $q$Improves curb appeal and safety for commercial properties; nationwide coverage across all 50 states.$q$, $q$commercial power washing, pressure washing, exterior cleaning, facade, sidewalks$q$, $q$24/7 claims; prices; guarantees; certifications; residential/home framing; DIY how-to$q$),
  ($q$jayco$q$, $q$Landscaping$q$, $q$Commercial landscaping and grounds maintenance for business properties, including lawn care, trimming, and seasonal upkeep.$q$, $q$Lawn mowing, hedge and tree trimming, bed maintenance, and seasonal cleanup for office parks, retail centers, and facility grounds.$q$, $q$Keeps commercial grounds professional and presentable; nationwide coverage across all 50 states.$q$, $q$commercial landscaping, grounds maintenance, lawn care, trimming, seasonal cleanup$q$, $q$24/7 claims; prices; guarantees; certifications; residential/home framing; DIY how-to$q$),
  ($q$jayco$q$, $q$Snow Removal$q$, $q$Commercial snow and ice removal for parking lots, walkways, and entrances to keep business properties safe and accessible in winter.$q$, $q$Plowing lots, clearing and de-icing walkways and entrances, and maintaining access for retail, offices, and facilities during winter weather.$q$, $q$Reduces slip hazards and keeps commercial properties open in winter; nationwide coverage across all 50 states.$q$, $q$commercial snow removal, ice removal, plowing, de-icing, winter maintenance$q$, $q$24/7 claims; prices; guarantees; certifications; residential/home framing; DIY how-to$q$),
  ($q$jayco$q$, $q$Junk Removal$q$, $q$Commercial junk and debris removal for offices, retail, and facilities, including furniture, equipment, and renovation debris.$q$, $q$Clearing old furniture, fixtures, equipment, and construction/renovation debris from commercial spaces and back-of-house areas.$q$, $q$Frees up commercial space and supports turnovers and renovations; nationwide coverage across all 50 states.$q$, $q$commercial junk removal, debris removal, furniture removal, cleanouts, renovation debris$q$, $q$24/7 claims; prices; guarantees; certifications; residential/home framing; DIY how-to$q$),
  ($q$huax$q$, $q$Preventive Maintenance$q$, $q$Planned commercial facility inspections and recurring maintenance designed to address upkeep before it becomes disruptive.$q$, $q$Recurring inspections, scheduled maintenance, multi-site upkeep, and coordination across commercial portfolios.$q$, $q$Nationwide multi-site support with coordinated facility service from one provider.$q$, $q$preventive maintenance, scheduled service, inspections, facility upkeep, multi-site$q$, $q$prices; guarantees; unverified certifications; invented results; DIY how-to; claims beyond the Hawks website$q$),
  ($q$huax$q$, $q$Emergency Repairs$q$, $q$24/7/365 commercial emergency repair coordination for facility issues requiring prompt response.$q$, $q$Unexpected HVAC, electrical, plumbing, door, glass, appliance, or building problems that disrupt operations.$q$, $q$Around-the-clock nationwide coordination for commercial and multi-site properties.$q$, $q$emergency facility repair, 24/7/365, commercial response, urgent maintenance$q$, $q$prices; guarantees; unverified certifications; invented results; DIY how-to; claims beyond the Hawks website$q$),
  ($q$huax$q$, $q$Building Maintenance$q$, $q$Ongoing commercial building maintenance across core trades and facility needs.$q$, $q$Recurring work orders, common-area repairs, property upkeep, and operational maintenance.$q$, $q$Broad nationwide trade coverage for complex commercial facility portfolios.$q$, $q$building maintenance, commercial property upkeep, work orders, facility operations$q$, $q$prices; guarantees; unverified certifications; invented results; DIY how-to; claims beyond the Hawks website$q$),
  ($q$huax$q$, $q$HVAC$q$, $q$Commercial HVAC service for facility heating, cooling, ventilation, maintenance, and repair needs.$q$, $q$Comfort issues, equipment problems, maintenance visits, and operational HVAC support.$q$, $q$Integrated nationwide facility coordination for HVAC alongside other trades.$q$, $q$commercial HVAC, heating, cooling, ventilation, maintenance, repair$q$, $q$prices; guarantees; unverified certifications; invented results; DIY how-to; claims beyond the Hawks website$q$),
  ($q$huax$q$, $q$Electrical$q$, $q$Commercial electrical service for building and facility maintenance needs.$q$, $q$Electrical faults, lighting and fixture issues, repairs, and recurring facility work.$q$, $q$Electrical work coordinated through the same nationwide facility support operation.$q$, $q$commercial electrical, lighting, fixtures, electrical repair, facility maintenance$q$, $q$prices; guarantees; unverified certifications; invented results; DIY how-to; claims beyond the Hawks website$q$),
  ($q$huax$q$, $q$Plumbing$q$, $q$Commercial plumbing service including pressure testing, hydro jetting, drain snaking, camera inspections, and septic work listed on the website.$q$, $q$Leaks, clogged drains, line diagnostics, flow issues, pressure testing, and septic-related service.$q$, $q$Specialized diagnostic and drain capabilities within a nationwide facility program.$q$, $q$commercial plumbing, hydro jetting, drain snaking, camera inspection, pressure testing, septic$q$, $q$prices; guarantees; unverified certifications; invented results; DIY how-to; claims beyond the Hawks website$q$),
  ($q$huax$q$, $q$Appliances$q$, $q$Commercial appliance service supporting facility operations and installed equipment.$q$, $q$Appliance failures, maintenance needs, and repair coordination at commercial or multi-site properties.$q$, $q$Appliance service coordinated with HVAC, electrical, plumbing, and general facility work.$q$, $q$commercial appliances, appliance service, facility equipment, repair coordination$q$, $q$prices; guarantees; unverified certifications; invented results; DIY how-to; claims beyond the Hawks website$q$),
  ($q$huax$q$, $q$Construction$q$, $q$Commercial construction support for property improvements and facility projects.$q$, $q$Renovations, repairs, tenant improvements, and project-based facility work.$q$, $q$Construction support integrated with maintenance and trade coordination.$q$, $q$commercial construction, renovation, facility project, property improvement$q$, $q$prices; guarantees; unverified certifications; invented results; DIY how-to; claims beyond the Hawks website$q$),
  ($q$huax$q$, $q$Doors & Locksmith$q$, $q$Commercial door and locksmith service including rekeying, lock replacement, door hardware, and door replacement.$q$, $q$Access problems, damaged doors, lock changes, hardware failures, and security-related repairs.$q$, $q$One coordinated service for door, lock, and hardware needs across multi-site portfolios.$q$, $q$commercial locksmith, rekeying, lock replacement, door hardware, door replacement$q$, $q$prices; guarantees; unverified certifications; invented results; DIY how-to; claims beyond the Hawks website$q$),
  ($q$huax$q$, $q$General Contracting$q$, $q$General contracting support including website-listed flooring, board-up, tiling, and carpentry.$q$, $q$Finish repairs, interior improvements, protective board-up, flooring, tile, and carpentry tasks.$q$, $q$Multiple related scopes coordinated within a single nationwide facility program.$q$, $q$general contracting, flooring, board-up, tiling, carpentry, commercial repairs$q$, $q$prices; guarantees; unverified certifications; invented results; DIY how-to; claims beyond the Hawks website$q$),
  ($q$huax$q$, $q$Glass$q$, $q$Commercial glass service for facility and property needs.$q$, $q$Damaged storefront, door, window, partition, or building glass requiring service.$q$, $q$Glass work coordinated with door, locksmith, construction, and emergency facility support.$q$, $q$commercial glass, storefront glass, window glass, glass repair, facility service$q$, $q$prices; guarantees; unverified certifications; invented results; DIY how-to; claims beyond the Hawks website$q$),
  ($q$huax$q$, $q$Vendor & Facility Support$q$, $q$Nationwide vendor and facility support for coordinating work across properties and service categories.$q$, $q$Multi-site work-order coordination, vendor support, recurring maintenance, and diverse trade needs.$q$, $q$Centralized support for commercial portfolios that need accountable coordination across locations.$q$, $q$vendor support, facility support, multi-site coordination, nationwide service, work orders$q$, $q$prices; guarantees; unverified certifications; invented results; DIY how-to; claims beyond the Hawks website$q$),
  ($q$paip$q$, $q$HVAC$q$, $q$Commercial HVAC installation, repair, diagnostics, and preventive maintenance.$q$, $q$New installations, system faults, comfort problems, diagnostics, repairs, and planned maintenance.$q$, $q$24/7/365 service across Texas, Louisiana, Oklahoma, and Arizona.$q$, $q$commercial HVAC, installation, repair, diagnostics, preventive maintenance$q$, $q$nationwide coverage; service outside Texas, Louisiana, Oklahoma, or Arizona; prices; guarantees; unverified certifications; invented results; DIY how-to$q$),
  ($q$paip$q$, $q$Electrical$q$, $q$Commercial electrical service for facilities in the company's four-state service area.$q$, $q$Electrical faults, lighting, power, fixtures, and facility electrical maintenance.$q$, $q$Trade support coordinated with HVAC, plumbing, and general maintenance 24/7/365.$q$, $q$commercial electrical, facility power, lighting, electrical repair$q$, $q$nationwide coverage; service outside Texas, Louisiana, Oklahoma, or Arizona; prices; guarantees; unverified certifications; invented results; DIY how-to$q$),
  ($q$paip$q$, $q$Plumbing$q$, $q$Commercial plumbing service for facility maintenance and repair needs.$q$, $q$Leaks, drainage issues, fixtures, piping problems, and operational plumbing work.$q$, $q$24/7/365 commercial response within Texas, Louisiana, Oklahoma, and Arizona.$q$, $q$commercial plumbing, leaks, drains, fixtures, piping, facility maintenance$q$, $q$nationwide coverage; service outside Texas, Louisiana, Oklahoma, or Arizona; prices; guarantees; unverified certifications; invented results; DIY how-to$q$),
  ($q$paip$q$, $q$General Maintenance$q$, $q$General commercial facility maintenance for day-to-day operational needs.$q$, $q$Recurring work orders, minor repairs, property upkeep, and multi-trade maintenance.$q$, $q$One regional provider coordinating multiple core trades across four states.$q$, $q$general maintenance, facility upkeep, commercial repairs, work orders$q$, $q$nationwide coverage; service outside Texas, Louisiana, Oklahoma, or Arizona; prices; guarantees; unverified certifications; invented results; DIY how-to$q$),
  ($q$paip$q$, $q$Metal Studs & Framing$q$, $q$Commercial metal stud and framing services for construction and interior build-out needs.$q$, $q$Partitions, interior framing, tenant improvements, renovations, and construction support.$q$, $q$Specialty framing capability integrated with general facility maintenance.$q$, $q$metal studs, commercial framing, partitions, tenant improvement, build-out$q$, $q$nationwide coverage; service outside Texas, Louisiana, Oklahoma, or Arizona; prices; guarantees; unverified certifications; invented results; DIY how-to$q$),
  ($q$paip$q$, $q$Cameras & Speed Radar$q$, $q$Camera and speed radar system service, including security/CCTV and road camera applications listed on the website.$q$, $q$Security camera needs, CCTV systems, road cameras, monitoring equipment, and speed radar applications.$q$, $q$Specialty low-voltage/security-related capability alongside core facility trades.$q$, $q$security cameras, CCTV, road cameras, speed radar, monitoring systems$q$, $q$nationwide coverage; service outside Texas, Louisiana, Oklahoma, or Arizona; prices; guarantees; unverified certifications; invented results; DIY how-to$q$),
  ($q$smply$q$, $q$Handyman$q$, $q$Residential and commercial handyman support for practical construction and maintenance needs.$q$, $q$General repairs, small projects, property upkeep, and everyday maintenance tasks.$q$, $q$A straightforward Chicago-area facility solution coordinated with electrical, HVAC, and locksmith services.$q$, $q$handyman, property repair, maintenance, small projects, Chicago$q$, $q$24/7 claims; emergency availability; nationwide coverage; prices; guarantees; unverified certifications; invented results; DIY how-to$q$),
  ($q$smply$q$, $q$Electrical$q$, $q$Electrical work for residential, commercial, and industrial settings as described on the website.$q$, $q$Electrical installation, repair, maintenance, and property improvement needs.$q$, $q$Electrical capability within a broader construction and maintenance service offering.$q$, $q$electrical, residential electrical, commercial electrical, industrial electrical, Chicago$q$, $q$24/7 claims; emergency availability; nationwide coverage; prices; guarantees; unverified certifications; invented results; DIY how-to$q$),
  ($q$smply$q$, $q$HVAC$q$, $q$HVAC service for residential and commercial construction and maintenance needs.$q$, $q$Heating, cooling, ventilation, repairs, maintenance, and property projects.$q$, $q$HVAC support coordinated with the company's handyman, electrical, and locksmith work.$q$, $q$HVAC, heating, cooling, ventilation, residential, commercial, Chicago$q$, $q$24/7 claims; emergency availability; nationwide coverage; prices; guarantees; unverified certifications; invented results; DIY how-to$q$),
  ($q$smply$q$, $q$Locksmith$q$, $q$Residential and commercial locksmith service for property access and security needs.$q$, $q$Locks, keys, doors, access issues, and property maintenance projects.$q$, $q$Locksmith support integrated with broader construction and maintenance services.$q$, $q$locksmith, locks, keys, doors, access, residential, commercial, Chicago$q$, $q$24/7 claims; emergency availability; nationwide coverage; prices; guarantees; unverified certifications; invented results; DIY how-to$q$)
on conflict (brand_id, service_value) do update set summary = excluded.summary, scenarios = excluded.scenarios, differentiators = excluded.differentiators, keywords = excluded.keywords, avoid = excluded.avoid;
